openapi: 3.1.0
info:
  version: 1.0.0
  title: VTEX IO
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAVIAAACVCAMAAAA9kYJlAAAAkFBMVEUUIDL///8IGC1MUVsADycADCUMGi4QHTAAAB+Ag4kSHzEAAB0AEyk7RFJIT1wAABsAACGLj5YAABcABiMAAAD09faTl52qrbLKy80AABX5+fp3fIRbYGq5vMBRV2LS09YAABBobXaeoabs7e4uN0bg4eNla3QaJjcmMD/CxMg9RVKztbp+gYfi5Oaipas0PUzYaRs6AAAEYUlEQVR4nO3ai3KqOhQGYKEhwRgriFfUKtiKl9q+/9vtlQACtrPtPttzOE7+b6bVIu3g7zKXZTsdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAxye4+1tctH2Fj8bLnm7YR21f42PxF2PnhngybPsqH4m7vBWotlBtX+cDCaY/ifTQa/s6H0j0o0hXftvX+UDcl59EusQb/w/MZ7cTXW/avsqH4h5vR/ritn2Vj6W3upUoJqc/xPu3Ij3ytq/xcYioNxgMRjcm/dMgP5t5Xj4ASLon9LcCk/TCeP5g4EeqI+mAmczE5XyLiCydaWvn9N6te2tEKvI9PgvDcKkzklkYTvqiG5a6HRkdw8NstkoXKpuE4YLRH5f0SGJbpkE5ip5HrM5vDAUfxZp0eKapX+9MVUJHnzrVPjbeR4vi7pgx/XrQoiuY0O3OtsXX4FxmkjWaTSaN0rh8LErphw794J/oRWBZPVIeF3e3zO3T/e2Qv9aGDHtUm9GP+u5IiLgW6SQoDrvPedlJj+rw1JPJIunSkZBulW4UpC/kiXd8/YKkI1rujl3r2oJ8H1/qrPbkex/1IvVkcVjyLWUf0G85uo8ilYo+6d4xUopRtjFTurdK523OunlFDyVeK0+rVX56PasT/lkv0kUVS+/gOG+RNPmZ0cAsv54pRXOo5wdBQPNSXs7kYGNLULiXAfH1svbsnWqJnn15OZvpOWgvdLLruT7QiNT5INOuztQ3A0r8aeVyNgrL7C4lZeaVi4RVJws9TiRsSN8nps/fjNRY62oXwVYPsnZ2r6S/LcMo9/HDQy3Rda1IO5352nFWc926yguwGWlMnIPO0cxWzqzxu/Zg72V6s55JoBwIc82mXkRzznhE37YDc25zLP0kfT3NyeDtehi2Sfn0dZnq+KRf7/VdNfW4nuEzKtVT/p5uRso40bOWGU1odBgL69ZQBksa+anGR1HPV/vJDc1mU/pK8uKtIqVaj3kQRZHeiXbo6Er/2dX8P386/wvzS5nq3eOmvr3/0tTz8x1s/JqX3yVS89HAYZKmaajkUJ+UbWZfxg1rVJ+UvHlC7epF2r9eBRU1vC6ivkQqWDnLjRXT50wCntHN2b7tk1YbPRebeb1Iv+7QJZvVxwOuPxB40rmrZZHpmCm6t1XSzGXO1M5/qqjm+DhtNPi/+ccdwZJpuC/fzjLbLXfCTP5K7dLpNFw8c31Mr7Gku1zullau9mkl+v0nJel3S3WpIq9KWrpKFYtPoaIg8BSnM5Ti5YOWJpr3QYxp7X95xpmV4+Cd9Iom33iUVpGGdg6DdyKKJl8YVH3lLbNzO3kvgalOmqerfv67nbvJuxFcVyftyeWmKNPzHEX6d/S29KD7Jl7Rpqs39eAfYfsj0zO8MB9wOusARfrXBM9DdPuU6Xpv64LyX+Gy52OERO9Kco53PQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgPELKQdAs6ikTQgAAAAASUVORK5CYII='
  description:
    $ref: ./info-description.md
tags:
  - name: VTEX Storefront
    description: Example echo operations.
  - name: Comandos de VTEX
    description: Operations about users.
  - name: Workspace
    description: This is a tag description.
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'
paths:
  '/users/{username}':
    $ref: 'paths/users_{username}.yaml'
  /echo:
    $ref: paths/echo.yaml
  /pathItem:
    $ref: paths/path-item.yaml
  /pathItemWithExamples:
    $ref: paths/path-item-with-examples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
